apiVersion: "elasticsearch.zerbytes.net/v1alpha1"
kind: "Elasticsearch"
metadata:
  name: "example"
spec:
  version: "5.4.0"
  # automatically calculate java memory opts
  # not implemented yet
  javaMemoryControl: true
  # this is currently not implemented due to it being missing
  # from the used k8s go-client
  #imagePullSecrets: "example"
  paused: false
#  imagePullSecrets: "example"
  # config that is added to *all* autogenrated config file
  additionalConfig: |
    action.auto_create_index: .security,.monitoring*,.watches,.triggered_watches,.watcher-history*,filebeat-*,metricbeat-*,packetbeat-*,winlogbeat-*,heartbeat-*
  master:
    replicas: 1
    #nodeSelector:
    #  elasticsearch-data: "yes"
    #baseImage: "quay.io/.."
    #resources:
    #  limits:
    #    memory: "512Mi"
    #  requests:
    #    memory: "512Mi"
    # add to the jvm.options file
    javaOpts: |
      # your additional java opts here
    additionalConfig: |
      # your addtional elasticsearch configuration here
    #storage:
    #  class: rbd
    #  resources:
    #    requests:
    #      storage: 10Gi
  data:
    replicas: 1
    #nodeSelector:
    #  elasticsearch-data: "yes"
    #baseImage: "quay.io/.."
    #resources:
    #  limits:
    #    memory: "512Mi"
    #  requests:
    #    memory: "512Mi"
    javaOpts: |
      # your additional java opts here
    additionalConfig: |
      # your addtional elasticsearch configuration here
    #storage:
    #  class: rbd
    #  resources:
    #    requests:
    #      storage: 15Gi
  ingest:
    replicas: 1
    #nodeSelector:
    #  elasticsearch-data: "yes"
    #baseImage: "quay.io/.."
    #resources:
    #  limits:
    #    memory: "512Mi"
    #  requests:
    #    memory: "512Mi"
    javaOpts: |
      # your additional java opts here
    additionalConfig: |
      # your addtional elasticsearch ingest configuration here
